commonLabels:
  app.kubernetes.io/genereted-by: JHipster

resources:
  # Individual apps
  - jhi-k8s/jhi-deployment.yml
  - jhi-k8s/jhi-service.yml
  - jhi-k8s/jhi-postgresql.yml
  - jhi-k8s/jwt-secret.yml
# service discovery eureka/consul

patchesJson6902:
