apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: tiamatz/jhi
      context: ../jhi
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
